# Generated by Django 4.1 on 2022-10-28 03:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('nomor_induk_kependudukan', models.BigIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(2000000000000000), django.core.validators.MaxValueValidator(10000000000000000)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dokter',
            fields=[
                ('nomor_induk_kependudukan', models.BigIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(2000000000000000), django.core.validators.MaxValueValidator(10000000000000000)])),
                ('nama_rumah_sakit', models.CharField(max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
