# Generated by Django 4.1 on 2022-10-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrasi', '0002_alter_dokter_nomor_induk_kependudukan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokter',
            name='nomor_induk_kependudukan',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='nomor_induk_kependudukan',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
