# Generated by Django 4.1 on 2022-10-25 20:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nomor_induk_kependudukan', models.BigIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(2000000000000000), django.core.validators.MaxValueValidator(10000000000000000)])),
                ('nama_pengguna', models.CharField(max_length=64)),
                ('adalah_pasien', models.BooleanField(default=False)),
                ('adalah_dokter', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Dokter',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nama_rumah_sakit', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
