# Generated by Django 4.1 on 2022-10-25 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keluhan',
            fields=[
                ('tanggal', models.DateField(primary_key=True, serialize=False)),
                ('tema', models.CharField(max_length=120)),
                ('deskripsi', models.TextField()),
                ('dokter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.dokter')),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.pasien')),
            ],
        ),
    ]
