# Generated by Django 4.1 on 2022-11-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=120)),
                ('produsen', models.CharField(max_length=120)),
                ('deskripsi', models.TextField()),
                ('efek_samping', models.TextField()),
            ],
        ),
    ]
