# Generated by Django 4.1 on 2022-11-01 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrasi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penyakit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_penyakit', models.CharField(max_length=255)),
                ('tanggal_diagnosis', models.DateField(auto_now_add=True)),
                ('deskripsi_keluhan', models.TextField()),
                ('sembuh', models.BooleanField(default=False)),
                ('dokter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrasi.dokter')),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrasi.pasien')),
            ],
        ),
    ]
