# Generated by Django 4.1 on 2022-10-31 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrasi', '0003_alter_dokter_nomor_induk_kependudukan_and_more'),
        ('dokter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='penyakit',
            old_name='user',
            new_name='pasien',
        ),
        migrations.AddField(
            model_name='penyakit',
            name='dokter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='registrasi.dokter'),
            preserve_default=False,
        ),
    ]
